<?xml version="1.0" encoding="utf-8"?><Database Name="Database" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\Database.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Item" Member="Items">
    <Type Name="Item">
      <Column Name="itemid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="uid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[itemcatogory ]" Member="itemcatogory_" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="itemtitle" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="itemdiscription" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="itemstate" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="itemimage" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="itemphone" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.LoginInfo" Member="LoginInfos">
    <Type Name="LoginInfo">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="uname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="upassword" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="uemail" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>